steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/poc-1-aima-pmu/aima-web', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/poc-1-aima-pmu/aima-web']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'aima-web'
    - '--image'
    - 'gcr.io/poc-1-aima-pmu/aima-web'
    - '--region'
    - 'us-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--set-env-vars'
    - 'NODE_ENV=production'
    - '--set-secrets'
    - 'SMTP_HOST=SMTP_HOST:latest'
    - '--set-secrets'
    - 'SMTP_PORT=SMTP_PORT:latest'
    - '--set-secrets'
    - 'SMTP_USER=SMTP_USER:latest'
    - '--set-secrets'
    - 'SMTP_PASS=SMTP_PASS:latest'

images:
  - 'gcr.io/poc-1-aima-pmu/aima-web'