services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASS
    restart: unless-stopped