name: Blue-Green Deployment to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: poc-1-aima-pmu
  SERVICE_NAME: aima-web
  REGION: us-west1
  SERVICE_ACCOUNT: github-actions@poc-1-aima-pmu.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker authentication
      run: gcloud auth configure-docker gcr.io

    - name: Generate version and revision suffix
      id: versioning
      run: |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        REVISION_SUFFIX="rc-${TIMESTAMP}"
        
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
        echo "REVISION_SUFFIX=$REVISION_SUFFIX" >> $GITHUB_ENV

    - name: Build and push Docker image
      env:
        IMAGE_NAME: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ env.TIMESTAMP }}
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Deploy New Revision
      run: |
        # Get current serving revision
        CURRENT_REVISION=$(gcloud run revisions list \
          --service=${{ env.SERVICE_NAME }} \
          --region=${{ env.REGION }} \
          --filter="traffic_percent>0" \
          --format="value(metadata.name)" \
          --limit=1)

        # Check current deployment state
        CURRENT_STATE=$(gcloud run revisions describe $CURRENT_REVISION \
          --region=${{ env.REGION }} \
          --format="value(labels.state)" || echo "active")

        # Determine new state (if current is active, deploy passive, and vice versa)
        NEW_STATE=$([ "$CURRENT_STATE" = "active" ] && echo "passive" || echo "active")
        
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ env.TIMESTAMP }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 \
          --service-account ${{ env.SERVICE_ACCOUNT }} \
          --min-instances 1 \
          --memory 512Mi \
          --revision-suffix=${{ env.REVISION_SUFFIX }} \
          --labels=state=$NEW_STATE \
          --no-traffic \
          --timeout 300 \
          --execution-environment gen2 \
          --cpu=1 \
          --set-env-vars STARTUP_CPU_BOOST=true

        # Ensure traffic stays with current revision during testing
        if [ -n "$CURRENT_REVISION" ]; then
          gcloud run services update-traffic ${{ env.SERVICE_NAME }} \
            --region=${{ env.REGION }} \
            --to-revisions=$CURRENT_REVISION=100
        fi

        echo "NEW_STATE=$NEW_STATE" >> $GITHUB_ENV
        echo "CURRENT_REVISION=$CURRENT_REVISION" >> $GITHUB_ENV

    - name: Test Passive Revision
      id: test
      run: |
        sleep 30
        NEW_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
          --region=${{ env.REGION }} \
          --format="value(status.url)")

        echo "Testing URL: $NEW_URL"

        MAX_RETRIES=3
        RETRY_COUNT=0
        SUCCESS=false

        while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ "$SUCCESS" = false ]; do
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$NEW_URL")

          if [ "$HTTP_STATUS" -eq 200 ]; then
            SUCCESS=true
            echo "status=success" >> $GITHUB_ENV
            break
          else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            echo "Attempt $RETRY_COUNT failed with status $HTTP_STATUS"
            [ $RETRY_COUNT -lt $MAX_RETRIES ] && sleep 10
          fi
        done

        if [ "$SUCCESS" = false ]; then
          echo "status=failure" >> $GITHUB_ENV
          exit 1
        fi

    - name: Migrate traffic to new revision
      if: env.status == 'success'
      run: |
        NEW_REVISION="${{ env.SERVICE_NAME }}-${{ env.REVISION_SUFFIX }}"
        
        gcloud run services update-traffic ${{ env.SERVICE_NAME }} \
          --region=${{ env.REGION }} \
          --to-revisions=$NEW_REVISION=100

    - name: Cleanup old revisions (keep last 5)
      if: always()
      run: |
        set -e
        REVISIONS=$(gcloud run revisions list \
          --service ${{ env.SERVICE_NAME }} \
          --region=${{ env.REGION }} \
          --format='value(metadata.name)' \
          --sort-by=~metadata.creationTimestamp --limit=1000)

        COUNT=0
        for REVISION in $REVISIONS; do
          COUNT=$((COUNT + 1))
          if [ $COUNT -gt 5 ]; then
            gcloud run revisions delete $REVISION \
              --region=${{ env.REGION }} \
              --quiet || true
          fi
        done

    - name: Rollback on Failure
      if: failure()
      run: |
        CURRENT_REVISION=$(gcloud run revisions list \
          --service=${{ env.SERVICE_NAME }} \
          --region=${{ env.REGION }} \
          --filter="traffic_percent>0" \
          --format="value(metadata.name)" \
          --limit=1)

        if [ -n "$CURRENT_REVISION" ]; then
          echo "Rolling back to: $CURRENT_REVISION"
          gcloud run services update-traffic ${{ env.SERVICE_NAME }} \
            --region=${{ env.REGION }} \
            --to-revisions=$CURRENT_REVISION=100
        fi

    - name: Cleanup Failed Revision
      if: failure()
      run: |
        NEW_REVISION="${{ env.SERVICE_NAME }}-${{ env.REVISION_SUFFIX }}"
        
        # Check if the new revision exists
        if gcloud run revisions describe $NEW_REVISION --region=${{ env.REGION }} &>/dev/null; then
          echo "Cleaning up failed revision: $NEW_REVISION"
          gcloud run revisions delete $NEW_REVISION \
            --region=${{ env.REGION }} \
            --quiet
        fi

      - name: Notify Deployment Status
      if: always()
      run: |
        NEW_REVISION="${{ env.SERVICE_NAME }}-${{ env.REVISION_SUFFIX }}"
        ENVIRONMENT="Production"
        STATUS="SUCCEEDED"
        if [ "${{ job.status }}" != "success" ]; then
          STATUS="FAILED"
        fi
        
        curl -X POST -H "Content-Type: application/json" \
        -d "{\"text\": \"[${ENVIRONMENT}] Deployment ${STATUS}\nService: ${{ env.SERVICE_NAME }}\nRevision: ${NEW_REVISION}\nRegion: ${{ env.REGION }}\"}" \
        ${{ secrets.SLACK_WEBHOOK_URL }}
