name: Blue-Green Deployment to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: poc-1-aima-pmu
  SERVICE_NAME: aima-web
  REGION: us-west1
  SERVICE_ACCOUNT: github-actions@poc-1-aima-pmu.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker authentication
      run: gcloud auth configure-docker gcr.io

    - name: Generate version and revision suffix
      id: versioning
      run: |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        VERSION="1.2.3"  # Change this to auto-fetch from package.json or a release tag

        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "BLUE_REVISION=blue-v$VERSION-$TIMESTAMP" >> $GITHUB_ENV
        echo "GREEN_REVISION=green-v$VERSION-$TIMESTAMP" >> $GITHUB_ENV

    - name: Build and push Docker image
      env:
        IMAGE_NAME: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }}
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Label current revision as Blue
      run: |
        gcloud run services update ${{ env.SERVICE_NAME }} \
          --region=${{ env.REGION }} \
          --revision-suffix=${{ env.BLUE_REVISION }} \
          --labels=deployment=blue,status=serving,version=${{ env.VERSION }}

    - name: Deploy new Green revision
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 \
          --service-account ${{ env.SERVICE_ACCOUNT }} \
          --min-instances 1 \
          --memory 512Mi \
          --revision-suffix=${{ env.GREEN_REVISION }} \
          --labels=deployment=green,version=${{ env.VERSION }} \
          --no-traffic \
          --timeout 300 \
          --execution-environment gen2 \
          --cpu=1 \
          --set-env-vars STARTUP_CPU_BOOST=true

    - name: Test new Green revision
      id: test
      run: |
        sleep 30
        NEW_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
          --region=${{ env.REGION }} \
          --format="value(status.url)")

        echo "Testing URL: $NEW_URL"

        MAX_RETRIES=3
        RETRY_COUNT=0
        SUCCESS=false

        while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ "$SUCCESS" = false ]; do
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$NEW_URL")
          
          if [ "$HTTP_STATUS" -eq 200 ]; then
            SUCCESS=true
            echo "status=success" >> $GITHUB_ENV
            break
          else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            echo "Attempt $RETRY_COUNT failed with status $HTTP_STATUS"
            [ $RETRY_COUNT -lt $MAX_RETRIES ] && sleep 10
          fi
        done

        if [ "$SUCCESS" = false ]; then
          echo "status=failure" >> $GITHUB_ENV
          exit 1
        fi

    - name: Migrate traffic to Green
      if: env.status == 'success'
      run: |
        gcloud run services update-traffic ${{ env.SERVICE_NAME }} \
          --region=${{ env.REGION }} \
          --to-revisions="${{ env.GREEN_REVISION }}=100"

    - name: Clean up failed revisions
      if: always()
      run: |
        set -e
        FAILED_REVISIONS=$(gcloud run revisions list \
          --service ${{ env.SERVICE_NAME }} \
          --region=${{ env.REGION }} \
          --filter="status.conditions.type='Ready' AND status.conditions.status='False'" \
          --format='value(metadata.name)')

        for REVISION in $FAILED_REVISIONS; do
          echo "Cleaning up failed revision: $REVISION"
          gcloud run revisions delete $REVISION \
            --region=${{ env.REGION }} \
            --quiet || true
        done

    - name: Cleanup old revisions (keep last 5)
      if: always()
      run: |
        set -e
        REVISIONS=$(gcloud run revisions list \
          --service ${{ env.SERVICE_NAME }} \
          --region=${{ env.REGION }} \
          --format='value(metadata.name)' \
          --sort-by=~metadata.creationTimestamp --limit=1000)

        COUNT=0
        for REVISION in $REVISIONS; do
          COUNT=$((COUNT + 1))
          if [ $COUNT -gt 5 ]; then
            gcloud run revisions delete $REVISION \
              --region=${{ env.REGION }} \
              --quiet || true
          fi
        done

    - name: Rollback on failure
      if: failure()
      run: |
        set -e
        BLUE_REVISION=$(gcloud run revisions list \
          --service=${{ env.SERVICE_NAME }} \
          --region=${{ env.REGION }} \
          --filter="labels.deployment=blue" \
          --format="value(metadata.name)" \
          --limit=1)

        if [ -n "$BLUE_REVISION" ]; then
          echo "Rolling back to Blue: $BLUE_REVISION"
          gcloud run services update-traffic ${{ env.SERVICE_NAME }} \
            --region=${{ env.REGION }} \
            --to-revisions=$BLUE_REVISION=100
        else
          echo "No Blue revision found, rollback not possible."
        fi
